version: 2.1

executors:
  arm:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: arm.medium

jobs:
  build-and-publish:
    executor: arm
    steps:
      - checkout
      - run: docker buildx build -t ghcr.io/nzws/osage.moe:$TAG-arm64 .
      - run: echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USER --password-stdin
      - run: docker push ghcr.io/nzws/osage.moe:$TAG-arm64

workflows:
  production:
    jobs:
      - build-and-publish:
          filters:
            branches:
              only: osage.moe
          pre-steps:
            - run: echo 'export TAG=production' >> "$BASH_ENV"
